# Generated by Django 2.2.5 on 2019-09-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=64)),
                ('gender', models.CharField(choices=[('M', 'Masculine'), ('F', 'Feminine')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Noun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=64)),
                ('female_up', models.PositiveIntegerField()),
                ('male_up', models.PositiveIntegerField()),
            ],
        ),
    ]
