# Generated by Django 2.2.5 on 2019-10-02 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gender', '0003_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noun',
            name='word',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
