# Generated by Django 2.2.5 on 2019-10-02 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gender', '0004_auto_20191002_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='word',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
